apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: speedtest-tracker
  name: speedtest-tracker-pv-claim
  labels:
    app: speedtest-tracker
spec:
  storageClassName: rook-cephfs   # use CephFS storage class name
  accessModes:
    - ReadWriteMany               # CephFS allows multiple writers
  resources:
    requests:
      storage: 1Gi