flask:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8000



worker:
  replicas: 1                    # Scale down from default (often 5+)
  resources:
  env:
    - name: MAX_CONCURRENT_ANALYSIS_JOBS
      value: "4"                 # Critical: limits parallel jobs per worker pod  
    

redis:
  enabled: true
  image: "redis:7-alpine"
  service:
    port: 6379
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"

postgres:
  user: "audiomuse"
  password: "iNh7BNyPPgVLe_c6bT" # IMPORTANT: Change this for production or use --set
  aiChatDbUser: "ai_user"
  aiChatDbUserPassword: "bwQEp2v2ZvU8_XL@Nz" # IMPORTANT: Change this for production or use --set
  service:
    port: 5432
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: "rook-cephfs" # Uncomment and specify if needed
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "2Gi"

# Credentials and external service configurations
# IMPORTANT: For production, manage these secrets securely, e.g., with Sealed Secrets or Vault.
emby:
  userid: "d29396b036d14875adbae9da8005557d"
  token: "5354e2a13c1e4adeb9eef80fac5971bb"
  url: "http://192.168.4.97:8096"

config:
  mediaServerType: "emby"
  aiModelProvider: "NONE" # Options: "GEMINI", "OLLAMA", "MISTRAL", or "NONE"
  #ollamaServerUrl: "http://192.168.3.15:11434/api/generate"
  #ollamaModelName: "mistral:7b"
  #geminiModelName: "gemini-1.5-flash-latest"
  #mistralModelName: "ministral-3b-latest"
  aiChatDbUserName: "ai_user"

analysis:
  numRecentAlbums: 50
