apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent2-config
  namespace: monitoring
data:
  zabbix_agent2.conf: |
    Server=192.168.4.72,10.42.0.0/16,10.0.0.0/8
    ServerActive=192.168.4.72
    Hostname=ceph-agent
    LogType=console
    Plugins.Prometheus.URL=http://rook-ceph-mgr.rook-ceph.svc.cluster.local:9283/metrics
    Plugins.Prometheus.Metrics=ceph_.*
    Plugins.Prometheus.Timeout=10s

