apiVersion: v1
kind: Pod
metadata:
  name: homepage-helper
  namespace: homepage
spec:
  containers:
    - name: helper
      image: alpine:3.20
      command: ["/bin/sh", "-c", "sleep 36000"]
      volumeMounts:
        - name: homepage-config
          mountPath: /config
  volumes:
    - name: homepage-config
      persistentVolumeClaim:
        claimName: homepage-pv-claim
