apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgejo-cert
  namespace: forgejo
spec:
  secretName: forgejo-tls
  dnsNames:
  - git.stone-lab.local
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
