apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie-cert
  namespace: mealie
spec:
  secretName: mealie-tls
  dnsNames:
  - mealie.stone-lab.local
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
